---
title: "Whither Weather Help"
author: "Dennis Noren"
output: html_document
---

### Getting Started

#### When the Whither Weather app opens, you see a list of cities. The idea is to select two cities for examination of their temperature patterns. You select by simply clicking on the city’s row (unselect by clicking again). Use the controls at the bottom to move to different pages. You can also search by typing text in the search box at the top (the search text applies to both city and state names). There are about 675 cities listed, all among the 48 co-terminus United States. The two most recently selected cities are the ones to be used. There are about 4600 weather stations used.  

### Getting Data Displayed

#### Then select the Temperature tab at the top, which transfers you to a different display. You can accept all default values and click the ‘Go’ button to see a result, but you will have to wait for the data to appear. This is because there are several API calls to be made to the NOAA website. The response time depends mostly on the length of the range of dates requested. The app does this processing:  
##### - Grabs the two selected cities,  
##### - Requests/receives data from nearby weather stations,
##### - Interpolates spatially among weather stations,  
##### - Interpolates temporally, in a linear fashion, when there are missing dates in a temperature series. 
##### - Displays and labels the data for the two cities, including the “normal” range between minimum and maximum as a light blue band,  
##### - Displays the number of stations used, and if you hover the cursor over this, displays the distances to stations.

### Varying the Results

#### You can then interact with the displayed data and make new data requests. The plotted daily values will probably have a very jagged appearance, especially if you have selected multiple years, but you can use controls to change this:  
##### - Use your mouse within a plot to select a particular date, and the exact data values will appear at the top of the plot.  
##### - Drag the cursor across a range of dates in either the top or bottom plot; this will zoom in for both plots, stretching the data horizontally across the plot area. To return to the full date range, double click within either plot.  
##### - Notice the small numeric value displayed on the lower left corner of both plots. To apply a moving average, change this to a higher value and type ‘return’ to activate. This is applied immediately; a value somewhere between 5 and 20 is a reasonable choice, but feel free to experiment.  
##### - On the left panel, you can select and apply different begin and end dates. To select dates, click on the existing date and interact with the selector; use small arrows to move forward or backward. Click on the month description at top, and it changes to year -- you can then jump forward and backward a year at a time. Click again on the year and it changes to decade. Remember to select a particular day. After selection, you must select the ‘Go’ button to initiate the request. Then you wait again for the requests to be made and the data to be processed.  
##### - The left panel also allows you to change the search radius for stations (up to a maximum of 50) and the maximum number of stations (up to a maximum of 10). Each city has one latitude/longitude centroid to represent its location, and the same is true for each weather station. The app gives more weight to the stations that are closer to the city.  
##### - For the Butterworth high pass filter, you might want to select a higher filter frequency than the default, say 12, 13, or 14, which will smooth/generalize more. Moving the frequency below 8 might not be a useful transformation because it will accentuate the day-by-day variations.  
##### - NOTE: The linear temporal interpolation does not try to extrapolate at the beginning or end of a requested date window. You will see the data series truncated, though this happens infrequently. When it does happen, the high pass filter will fail. The primary solution is to change the date window so there are no missing values at the beginning or end.  
##### - NOTE: If a high pass filter fails apart from the above situation, and there happens to be only one weather station for that city, try increasing the search radius to include one or more additional stations. It's not known why this happens, but this workaround is sometimes successful.  
##### - You can continue to try new input parameter combinations on the selected cities, or return to the Cities tab to select new cities.  Whenever an input changes, you must select the 'Go' button again to get new results.  
##### - Select the ‘Close’ button to close the application.

